name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 black psycopg2-binary pymongo

      - name: Check formatting and indentation
        continue-on-error: true
        run: |
          echo "Checking style with flake8..."
          flake8 --max-line-length=120 . || true
          echo "Formatting code with black (check mode)..."
          black --check . || true

      - name: Run main script
        env:
          MONGO_URI: mongodb://localhost:27017
          POSTGRES_URL: postgresql://testuser:testpass@localhost:5432/testdb
        run: |
          echo "Running script seed.py..."
          python seed.py

      - name: Pipeline finished successfully
        run: echo "Everything ran correctly!"
